apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginAds
spec:
  enabled: true
  version: 1.0.0
  requires: ">=2.0.0"
  author:
    name: ihxx
    website: https://github.com/git-kings
  logo: favicon.ico
  settingName: plugin-ads-settings
  configMapName: plugin-ads-settings
  homepage: https://github.com/git-kings/plugin-ads
  displayName: "Ads文件"
  description: "为站点提供谷歌广告Ads.txt"
  license:
    - name: "MIT"
